############################################
# Namespace Configuration for Demo App
############################################
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app

---
############################################
# Deployment for Demo App (Pulling Image from AWS ECR)
############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/demo-app
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
      imagePullSecrets:
        - name: ecr-secret  # ✅ Secret dynamically created via CI/CD

---
############################################
# Service to Expose Demo App
############################################
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
