apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: demo-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # ✅ AWS Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
